### ISSUE TITLE
DNS-Settings missing

### ISSUE THREAD

**Issue by Gill-Bates** [precisionpete/wgadmin#2]
Hey there,

where can I define an own DNS-Server?

**Comment by precisionpete** [comment]
It does not currently handle custom DNS. It just uses what your PCs are configured to use. The goal was to keep it simple for the uninitiated.

However, might not be a bad idea to add that.

In the end, it's WireGuard. So you can add more lines to the config files.

**Comment by Gill-Bates** [comment]
> In the end, it's WireGuard. So you can add more lines to the config files.

Not really, because `wg0.conf` will be overwritten and I have no clue where wgadmin stores the conf-Files.

```
# This config is automatically generated by wgadmin.
# It is for your reference only and is not used by wgadmin.
# Any commands placed here will be overwritten.
```

**Comment by precisionpete** [comment]
Good point. You can modify the client files but not the server.

The client conf files are generated each time you view them. But you can modify them once they are downloaded. But without the server I see there is an issue.

I will add the DNS. Is there anything else you were hoping for?

**Comment by precisionpete** [comment]
I just updated the binaries to reflect adding the DNS setting. The DNS is optional and is set on the Server page. It is then inherited by each client config as they are downloaded. i.e. you will have to download a new version for each client.

Please let me know what you think. All feedback is welcome!

**Comment by precisionpete** [comment]
I just updated 0.1.2 to include the DNS feature. It's on the Server and the clients inherit the setting. Obviously, you need to download the client configs again... The wgadmin tunnels on the server have to be restarted to pick it up if you change the setting.

It was more work than I thought. Now, I remember why I skipped it the first time around.

Please let me know how it works for you. All feedback os good feedback.

**Comment by Gill-Bates** [comment]
Thanks! I can confirm, that in wgadmin Version 1.2. the DNS Settings are available.
